import { ContainerOperator } from "../../containers.mjs";
import { Lift, TReactive } from "../../containers/__internal__/containers.internal.mjs";
import { Function1 } from "../../functions.mjs";
import { ObserverLike, ObservableLike } from "../../rx.mjs";
declare const liftObservable: <TA, TB>(operator: Function1<ObserverLike<TB>, ObserverLike<TA>>) => ContainerOperator<ObservableLike<unknown>, TA, TB>;
declare const liftObservableT: Lift<ObservableLike, TReactive>;
declare const liftRunnableObservable: <TA, TB>(operator: Function1<ObserverLike<TB>, ObserverLike<TA>>) => ContainerOperator<ObservableLike<unknown>, TA, TB>;
declare const liftEnumerableObservable: <TA, TB>(operator: Function1<ObserverLike<TB>, ObserverLike<TA>>) => ContainerOperator<ObservableLike<unknown>, TA, TB>;
declare const liftEnumerableObservableT: Lift<ObservableLike, TReactive>;
export { liftEnumerableObservable, liftEnumerableObservableT, liftObservable, liftObservableT, liftRunnableObservable };
