import { EnumerableLike } from "../../ix";
import Enumerable from "../../ix/Enumerable";
import {
  bufferTests,
  concatAllTests,
  concatMapTests,
  concatTests,
  concatWithTests,
  distinctUntilChangedTests,
  endWithTests,
  forEachTests,
  genMapTests,
  ignoreElementsTests,
  keepTests,
  mapTests,
  mapToTests,
  pairwiseTests,
  repeatTests,
  scanTests,
  skipFirstTests,
  startWithTests,
  takeFirstTests,
  takeLastTests,
  takeWhileTests,
  throwIfEmptyTests,
  zipTests,
  zipWithTests,
} from "../operators";
import { testModule } from "../testing";

testModule(
  "Enumerable",
  bufferTests(Enumerable),
  concatTests<EnumerableLike>(Enumerable),
  concatAllTests(Enumerable),
  concatMapTests(Enumerable),
  concatWithTests(Enumerable),
  distinctUntilChangedTests(Enumerable),
  endWithTests(Enumerable),
  forEachTests(Enumerable),
  genMapTests(Enumerable),
  ignoreElementsTests(Enumerable),
  keepTests(Enumerable),
  mapTests(Enumerable),
  mapToTests(Enumerable),
  pairwiseTests(Enumerable),
  repeatTests(Enumerable),
  scanTests(Enumerable),
  skipFirstTests(Enumerable),
  startWithTests(Enumerable),
  takeFirstTests(Enumerable),
  takeLastTests(Enumerable),
  takeWhileTests(Enumerable),
  throwIfEmptyTests(Enumerable),
  zipTests(Enumerable),
  zipWithTests(Enumerable),
);
