import { EnumerableLike } from "../../ix";
import {
  buffer,
  concat,
  concatAll,
  distinctUntilChanged,
  forEach,
  fromArray,
  keep,
  map,
  pairwise,
  repeat,
  scan,
  skipFirst,
  takeFirst,
  takeLast,
  takeWhile,
  throwIfEmpty,
  toReadonlyArray,
  zip,
} from "../../ix/Enumerable";
import {
  bufferTests,
  concatAllTests,
  concatTests,
  distinctUntilChangedTests,
  forEachTests,
  keepTests,
  mapTests,
  pairwiseTests,
  repeatTests,
  scanTests,
  skipFirstTests,
  takeFirstTests,
  takeLastTests,
  takeWhileTests,
  throwIfEmptyTests,
  zipTests,
} from "../operators";
import { testModule } from "../testing";

testModule(
  "Enumerable",
  bufferTests({
    fromArray,
    buffer,
    toReadonlyArray,
  }),
  concatTests<EnumerableLike>({
    fromArray,
    concat,
    toReadonlyArray,
  }),
  concatAllTests({
    fromArray,
    concatAll,
    toReadonlyArray,
  }),
  distinctUntilChangedTests({
    fromArray,
    distinctUntilChanged,
    toReadonlyArray,
  }),
  forEachTests({
    fromArray,
    forEach,
    toReadonlyArray,
  }),
  keepTests({
    fromArray,
    keep,
    toReadonlyArray,
  }),
  mapTests({
    fromArray,
    map,
    toReadonlyArray,
  }),
  pairwiseTests({
    fromArray,
    pairwise,
    toReadonlyArray,
  }),
  repeatTests({
    fromArray,
    repeat,
    takeFirst,
    toReadonlyArray,
  }),
  scanTests({
    fromArray,
    scan,
    toReadonlyArray,
  }),
  skipFirstTests({
    fromArray,
    skipFirst,
    toReadonlyArray,
  }),
  takeFirstTests({
    fromArray,
    takeFirst,
    toReadonlyArray,
  }),
  takeLastTests({
    fromArray,
    takeLast,
    toReadonlyArray,
  }),
  takeWhileTests({
    fromArray,
    takeWhile,
    toReadonlyArray,
  }),
  throwIfEmptyTests({
    fromArray,
    throwIfEmpty,
    toReadonlyArray,
  }),
  zipTests<EnumerableLike>({
    fromArray,
    zip,
    toReadonlyArray,
  }),
);
