import { SequenceLike } from "../../containers";
import Sequence from "../../containers/Sequence";
import {
  concatAllTests,
  concatMapTests,
  concatTests,
  concatWithTests,
  distinctUntilChangedTests,
  endWithTests,
  ignoreElementsTests,
  keepTests,
  mapTests,
  mapToTests,
  pairwiseTests,
  repeatTests,
  scanTests,
  skipFirstTests,
  startWithTests,
  takeFirstTests,
  takeLastTests,
  takeWhileTests,
  zipTests,
  zipWithTests,
} from "../operators";
import { testModule } from "../testing";

testModule(
  "Sequence",
  concatTests<SequenceLike>(Sequence),
  concatAllTests(Sequence),
  concatMapTests(Sequence),
  concatWithTests<SequenceLike>(Sequence),
  distinctUntilChangedTests(Sequence),
  endWithTests<SequenceLike>(Sequence),
  ignoreElementsTests(Sequence),
  keepTests(Sequence),
  mapTests(Sequence),
  mapToTests(Sequence),
  pairwiseTests(Sequence),
  repeatTests(Sequence),
  scanTests(Sequence),
  skipFirstTests(Sequence),
  startWithTests<SequenceLike>(Sequence),
  takeFirstTests(Sequence),
  takeLastTests(Sequence),
  takeWhileTests(Sequence),
  zipTests<SequenceLike>(Sequence),
  zipWithTests<SequenceLike>(Sequence),
);
