import { SequenceLike } from "../../containers";
import {
  concat,
  concatAll,
  distinctUntilChanged,
  fromArray,
  keep,
  map,
  pairwise,
  repeat,
  scan,
  skipFirst,
  takeFirst,
  takeLast,
  takeWhile,
  toReadonlyArray,
  zip,
} from "../../containers/SequenceLike";
import {
  concatAllTests,
  concatTests,
  distinctUntilChangedTests,
  keepTests,
  mapTests,
  pairwiseTests,
  repeatTests,
  scanTests,
  skipFirstTests,
  takeFirstTests,
  takeLastTests,
  takeWhileTests,
  zipTests,
} from "../operators";
import { testModule } from "../testing";

testModule(
  "SequenceLike",
  concatTests<SequenceLike>({
    fromArray,
    concat,
    toReadonlyArray,
  }),
  concatAllTests({
    fromArray,
    concatAll,
    toReadonlyArray,
  }),
  distinctUntilChangedTests({
    fromArray,
    distinctUntilChanged,
    toReadonlyArray,
  }),
  keepTests({
    fromArray,
    keep,
    toReadonlyArray,
  }),
  mapTests({
    fromArray,
    map,
    toReadonlyArray,
  }),
  pairwiseTests({
    fromArray,
    pairwise,
    toReadonlyArray,
  }),
  repeatTests({
    fromArray,
    repeat,
    takeFirst,
    toReadonlyArray,
  }),
  scanTests({
    fromArray,
    scan,
    toReadonlyArray,
  }),
  skipFirstTests({
    fromArray,
    skipFirst,
    toReadonlyArray,
  }),
  takeFirstTests({
    fromArray,
    takeFirst,
    toReadonlyArray,
  }),
  takeLastTests({
    fromArray,
    takeLast,
    toReadonlyArray,
  }),
  takeWhileTests({
    fromArray,
    takeWhile,
    toReadonlyArray,
  }),
  zipTests<SequenceLike>({
    fromArray,
    zip,
    toReadonlyArray,
  }),
);
