import { ContainerOperator } from "../../../containers.mjs";
import { AsyncEnumerableLike } from "../../../ix.mjs";
import { ObservableLike } from "../../../rx.mjs";
interface CreateAsyncEnumerable {
    <A>(op1: ContainerOperator<ObservableLike, void, A>): AsyncEnumerableLike<A>;
    <A, B>(op1: ContainerOperator<ObservableLike, void, A>, op2: ContainerOperator<ObservableLike, A, B>): AsyncEnumerableLike<B>;
    <A, B, C>(op1: ContainerOperator<ObservableLike, void, A>, op2: ContainerOperator<ObservableLike, A, B>, op3: ContainerOperator<ObservableLike, B, C>): AsyncEnumerableLike<C>;
    <A, B, C, D>(op1: ContainerOperator<ObservableLike, void, A>, op2: ContainerOperator<ObservableLike, A, B>, op3: ContainerOperator<ObservableLike, B, C>, op4: ContainerOperator<ObservableLike, C, D>): AsyncEnumerableLike<D>;
    <A, B, C, D, E>(op1: ContainerOperator<ObservableLike, void, A>, op2: ContainerOperator<ObservableLike, A, B>, op3: ContainerOperator<ObservableLike, B, C>, op4: ContainerOperator<ObservableLike, C, D>, op5: ContainerOperator<ObservableLike, D, E>): AsyncEnumerableLike<E>;
    <A, B, C, D, E, F>(op1: ContainerOperator<ObservableLike, void, A>, op2: ContainerOperator<ObservableLike, A, B>, op3: ContainerOperator<ObservableLike, B, C>, op4: ContainerOperator<ObservableLike, C, D>, op5: ContainerOperator<ObservableLike, D, E>, op6: ContainerOperator<ObservableLike, E, F>): AsyncEnumerableLike<F>;
    <A, B, C, D, E, F, G>(op1: ContainerOperator<ObservableLike, void, A>, op2: ContainerOperator<ObservableLike, A, B>, op3: ContainerOperator<ObservableLike, B, C>, op4: ContainerOperator<ObservableLike, C, D>, op5: ContainerOperator<ObservableLike, D, E>, op6: ContainerOperator<ObservableLike, E, F>, op7: ContainerOperator<ObservableLike, F, G>): AsyncEnumerableLike<G>;
    <A, B, C, D, E, F, G, H>(op1: ContainerOperator<ObservableLike, void, A>, op2: ContainerOperator<ObservableLike, A, B>, op3: ContainerOperator<ObservableLike, B, C>, op4: ContainerOperator<ObservableLike, C, D>, op5: ContainerOperator<ObservableLike, D, E>, op6: ContainerOperator<ObservableLike, E, F>, op7: ContainerOperator<ObservableLike, F, G>, op8: ContainerOperator<ObservableLike, G, H>): AsyncEnumerableLike<H>;
    <A, B, C, D, E, F, G, H, I>(op1: ContainerOperator<ObservableLike, void, A>, op2: ContainerOperator<ObservableLike, A, B>, op3: ContainerOperator<ObservableLike, B, C>, op4: ContainerOperator<ObservableLike, C, D>, op5: ContainerOperator<ObservableLike, D, E>, op6: ContainerOperator<ObservableLike, E, F>, op7: ContainerOperator<ObservableLike, F, G>, op8: ContainerOperator<ObservableLike, G, H>, op9: ContainerOperator<ObservableLike, H, I>): AsyncEnumerableLike<I>;
    <A, B, C, D, E, F, G, H, I, J>(op1: ContainerOperator<ObservableLike, void, A>, op2: ContainerOperator<ObservableLike, A, B>, op3: ContainerOperator<ObservableLike, B, C>, op4: ContainerOperator<ObservableLike, C, D>, op5: ContainerOperator<ObservableLike, D, E>, op6: ContainerOperator<ObservableLike, E, F>, op7: ContainerOperator<ObservableLike, F, G>, op8: ContainerOperator<ObservableLike, G, H>, op9: ContainerOperator<ObservableLike, H, I>, op10: ContainerOperator<ObservableLike, I, J>): AsyncEnumerableLike<J>;
    <A, B, C, D, E, F, G, H, I, J, K>(op1: ContainerOperator<ObservableLike, void, A>, op2: ContainerOperator<ObservableLike, A, B>, op3: ContainerOperator<ObservableLike, B, C>, op4: ContainerOperator<ObservableLike, C, D>, op5: ContainerOperator<ObservableLike, D, E>, op6: ContainerOperator<ObservableLike, E, F>, op7: ContainerOperator<ObservableLike, F, G>, op8: ContainerOperator<ObservableLike, G, H>, op9: ContainerOperator<ObservableLike, H, I>, op10: ContainerOperator<ObservableLike, I, J>, op11: ContainerOperator<ObservableLike, J, K>): AsyncEnumerableLike<K>;
    <A, B, C, D, E, F, G, H, I, J, K, L>(op1: ContainerOperator<ObservableLike, void, A>, op2: ContainerOperator<ObservableLike, A, B>, op3: ContainerOperator<ObservableLike, B, C>, op4: ContainerOperator<ObservableLike, C, D>, op5: ContainerOperator<ObservableLike, D, E>, op6: ContainerOperator<ObservableLike, E, F>, op7: ContainerOperator<ObservableLike, F, G>, op8: ContainerOperator<ObservableLike, G, H>, op9: ContainerOperator<ObservableLike, H, I>, op10: ContainerOperator<ObservableLike, I, J>, op11: ContainerOperator<ObservableLike, J, K>, op12: ContainerOperator<ObservableLike, K, L>): AsyncEnumerableLike<L>;
}
declare const AsyncEnumerable__create: CreateAsyncEnumerable;
export { AsyncEnumerable__create as default };
