import { FromAsyncIterable } from "../containers.js";
import { FromEnumerable, FromIterable, FromOptional, FromReadonlyArray, Generate, GenerateLast, ObservableLike, ToEnumerable, ToObservable, ToRunnable } from "../rx.js";
import { AsyncEnumerableLike } from "../streaming.js";
export declare const fromIterable: FromIterable<AsyncEnumerableLike>["fromIterable"];
export declare const fromAsyncIterable: FromAsyncIterable<AsyncEnumerableLike>["fromAsyncIterable"];
export declare const fromEnumerable: FromEnumerable<AsyncEnumerableLike>["fromEnumerable"];
export declare const fromOptional: FromOptional<AsyncEnumerableLike>["fromOptional"];
export declare const fromReadonlyArray: FromReadonlyArray<AsyncEnumerableLike>["fromReadonlyArray"];
export declare const generate: Generate<AsyncEnumerableLike>["generate"];
export declare const generateLast: GenerateLast<AsyncEnumerableLike, ObservableLike>["generateLast"];
export declare const toEnumerable: ToEnumerable<AsyncEnumerableLike>["toEnumerable"];
export declare const toObservable: ToObservable<AsyncEnumerableLike>["toObservable"];
export declare const toRunnable: ToRunnable<AsyncEnumerableLike>["toRunnable"];
