// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Observable from "@reactive-js/observable";

var ObservableOperator = { };

var MergeAllConfig = { };

function x(param) {
  return Observable.throttle(10, 1);
}

export {
  ObservableOperator ,
  MergeAllConfig ,
  x ,
  
}
/* @reactive-js/observable Not a pure module */
