/// <reference types="./Producer.d.ts" />

import { Computation_baseOfT, Computation_deferredWithSideEffectsOfT, Computation_multicastOfT, Computation_pureDeferredOfT, Computation_pureSynchronousOfT, Computation_synchronousWithSideEffectsOfT, } from "../computations.js";
import { identity, returns } from "../functions.js";
import Producer_broadcast from "./Producer/__private__/Producer.broadcast.js";
import Producer_buffer from "./Producer/__private__/Producer.buffer.js";
import Producer_catchError from "./Producer/__private__/Producer.catchError.js";
import Producer_concat from "./Producer/__private__/Producer.concat.js";
import Producer_create from "./Producer/__private__/Producer.create.js";
import Producer_decodeWithCharset from "./Producer/__private__/Producer.decodeWithCharset.js";
import Producer_distinctUntilChanged from "./Producer/__private__/Producer.distinctUntilChanged.js";
import Producer_encodeUtf8 from "./Producer/__private__/Producer.encodeUtf8.js";
import Producer_forEach from "./Producer/__private__/Producer.forEach.js";
import { Producer_gen, Producer_genPure, } from "./Producer/__private__/Producer.gen.js";
import { Producer_genAsync, Producer_genPureAsync, } from "./Producer/__private__/Producer.genAsync.js";
import Producer_keep from "./Producer/__private__/Producer.keep.js";
import Producer_map from "./Producer/__private__/Producer.map.js";
import Producer_pairwise from "./Producer/__private__/Producer.pairwise.js";
import Producer_scan from "./Producer/__private__/Producer.scan.js";
import Producer_skipFirst from "./Producer/__private__/Producer.skipFirst.js";
import Producer_subscribe from "./Producer/__private__/Producer.subscribe.js";
import Producer_takeFirst from "./Producer/__private__/Producer.takeFirst.js";
import Producer_takeLast from "./Producer/__private__/Producer.takeLast.js";
import Producer_takeUntil from "./Producer/__private__/Producer.takeUntil.js";
import Producer_takeWhile from "./Producer/__private__/Producer.takeWhile.js";
import Producer_throwIfEmpty from "./Producer/__private__/Producer.throwIfEmpty.js";
import Producer_withLatestFrom from "./Producer/__private__/Producer.withLatestFrom.js";
export const buffer = Producer_buffer;
export const broadcast = Producer_broadcast;
export const catchError = Producer_catchError;
export const concat = Producer_concat;
export const create = Producer_create;
export const decodeWithCharset = Producer_decodeWithCharset;
export const distinctUntilChanged = Producer_distinctUntilChanged;
export const encodeUtf8 = Producer_encodeUtf8;
export const forEach = Producer_forEach;
export const gen = Producer_gen;
export const genAsync = Producer_genAsync;
export const genPure = Producer_genPure;
export const genPureAsync = Producer_genPureAsync;
export const keep = Producer_keep;
export const makeModule = identity;
export const map = Producer_map;
export const pairwise = Producer_pairwise;
export const scan = Producer_scan;
export const skipFirst = Producer_skipFirst;
export const subscribe = Producer_subscribe;
export const takeFirst = Producer_takeFirst;
export const takeLast = Producer_takeLast;
export const takeUntil = Producer_takeUntil;
export const takeWhile = Producer_takeWhile;
export const throwIfEmpty = Producer_throwIfEmpty;
export const toProducer = /*@__PURE__*/ returns(identity);
export const withLatestFrom = Producer_withLatestFrom;
