import { ForEach, Keep, Map, Pick } from "../containers.js";
import { Function1 } from "../functions.js";
import { DispatchTo, Enqueue, ObservableLike, PauseableObservableLike } from "../rx.js";
import { DispatcherLike } from "../util.js";
export declare const dispatchTo: DispatchTo<PauseableObservableLike>["dispatchTo"];
export declare const enqueue: Enqueue<PauseableObservableLike>["enqueue"];
export declare const forEach: ForEach<PauseableObservableLike>["forEach"];
export declare const keep: Keep<PauseableObservableLike>["keep"];
export declare const map: Map<PauseableObservableLike>["map"];
export declare const pick: Pick<PauseableObservableLike>["pick"];
export declare const sinkInto: <T>(sink: DispatcherLike<T>) => Function1<PauseableObservableLike<T>, ObservableLike<void>>;
