import { Keep, Map, ContainerOperator, Scan, ToReadonlyArray } from "../containers.mjs";
import { SideEffect1 } from "../functions.mjs";
import { RunnableLike } from "../rx.mjs";
declare const keep: Keep<RunnableLike>["keep"];
declare const keepT: Keep<RunnableLike>;
declare const map: Map<RunnableLike>["map"];
declare const mapT: Map<RunnableLike>;
declare const onNotify: <T>(onNotify: SideEffect1<T>) => ContainerOperator<RunnableLike, T, T>;
declare const run: <T>() => (runnable: RunnableLike<T>) => void;
declare const scan: Scan<RunnableLike>["scan"];
declare const scanT: Scan<RunnableLike>;
declare const toReadonlyArray: ToReadonlyArray<RunnableLike>["toReadonlyArray"];
declare const toReadonlyArrayT: ToReadonlyArray<RunnableLike>;
export { keep, keepT, map, mapT, onNotify, run, scan, scanT, toReadonlyArray, toReadonlyArrayT };
