import { Empty, Entries, ForEachWithKey, Keep, KeepType, KeepWithKey, KeySet, Keys, Map, MapWithKey, ReadonlyObjectMapContainerLike, ReadonlyObjectMapLike, Reduce, ReduceWithKey, Values } from "../keyed-containers.js";
export declare const empty: Empty<ReadonlyObjectMapContainerLike>["empty"];
export declare const entries: Entries<ReadonlyObjectMapContainerLike>["entries"];
export declare const forEachWithKey: ForEachWithKey<ReadonlyObjectMapContainerLike>["forEachWithKey"];
export declare const keep: Keep<ReadonlyObjectMapContainerLike>["keep"];
export declare const keepType: KeepType<ReadonlyObjectMapContainerLike>["keepType"];
export declare const keepWithKey: KeepWithKey<ReadonlyObjectMapContainerLike>["keepWithKey"];
export declare const keys: Keys<ReadonlyObjectMapLike>["keys"];
export declare const keySet: KeySet<ReadonlyObjectMapLike>["keySet"];
export declare const map: Map<ReadonlyObjectMapContainerLike>["map"];
export declare const mapWithKey: MapWithKey<ReadonlyObjectMapContainerLike>["mapWithKey"];
export declare const reduce: Reduce<ReadonlyObjectMapContainerLike>["reduce"];
export declare const reduceWithKey: ReduceWithKey<ReadonlyObjectMapContainerLike>["reduceWithKey"];
export declare const values: Values<ReadonlyObjectMapContainerLike>["values"];
