import { ConcatAll, SequenceLike, Concat, DistinctUntilChanged, Keep, Map, Pairwise, ContainerOperator, TakeFirst, Repeat, Scan, SkipFirst, TakeLast, TakeWhile, Zip } from "../containers.mjs";
import { ToEnumerable } from "../ix.mjs";
declare const concatAll: ConcatAll<SequenceLike>["concatAll"];
declare const concatAllT: ConcatAll<SequenceLike>;
declare function concat<T>(fst: SequenceLike<T>, snd: SequenceLike<T>, ...tail: readonly SequenceLike<T>[]): SequenceLike<T>;
declare const concatT: Concat<SequenceLike>;
declare const distinctUntilChanged: DistinctUntilChanged<SequenceLike>["distinctUntilChanged"];
declare const distinctUntilChangedT: DistinctUntilChanged<SequenceLike>;
declare const keep: Keep<SequenceLike>["keep"];
declare const keepT: Keep<SequenceLike>;
declare const map: Map<SequenceLike>["map"];
declare const mapT: Map<SequenceLike>;
declare const pairwise: Pairwise<SequenceLike>["pairwise"];
declare const pairwiseT: Pairwise<SequenceLike>;
declare const seek: <T>(count: number) => ContainerOperator<SequenceLike<unknown>, T, T>;
declare const takeFirst: TakeFirst<SequenceLike>["takeFirst"];
declare const takeFirstT: TakeFirst<SequenceLike>;
declare const repeat: Repeat<SequenceLike>["repeat"];
declare const repeatT: Repeat<SequenceLike>;
declare const scan: Scan<SequenceLike>["scan"];
declare const scanT: Scan<SequenceLike>;
declare const skipFirst: SkipFirst<SequenceLike>["skipFirst"];
declare const skipFirstT: SkipFirst<SequenceLike>;
declare const takeLast: TakeLast<SequenceLike>["takeLast"];
declare const takeLastT: TakeLast<SequenceLike>;
declare const takeWhile: TakeWhile<SequenceLike>["takeWhile"];
declare const takeWhileT: TakeWhile<SequenceLike>;
declare const toEnumerable: ToEnumerable<SequenceLike>["toEnumerable"];
declare const toEnumerableT: ToEnumerable<SequenceLike>;
declare const zip: Zip<SequenceLike>["zip"];
declare const zipT: Zip<SequenceLike>;
export { concat, concatAll, concatAllT, concatT, distinctUntilChanged, distinctUntilChangedT, keep, keepT, map, mapT, pairwise, pairwiseT, repeat, repeatT, scan, scanT, seek, skipFirst, skipFirstT, takeFirst, takeFirstT, takeLast, takeLastT, takeWhile, takeWhileT, toEnumerable, toEnumerableT, zip, zipT };
