/** @type {unique symbol} */
export const ContainerLike_T: unique symbol;
/** @type {unique symbol} */
export const ContainerLike_type: unique symbol;
/** @type {unique symbol} */
export const EnumeratorLike_move: unique symbol;
/** @type {unique symbol} */
export const EnumeratorLike_current: unique symbol;
/** @type {unique symbol} */
export const EnumeratorLike_hasCurrent: unique symbol;
