/** @type {unique symbol} */
export const DispatcherLike_complete: unique symbol;
/** @type {unique symbol} */
export const DispatcherLike_scheduler: unique symbol;
/** @type {unique symbol} */
export const MulticastObservableLike_observerCount: unique symbol;
/** @type {unique symbol} */
export const ObserverLike_notify: unique symbol;
/** @type {unique symbol} */
export const ObservableLike_observe: unique symbol;
/** @type {unique symbol} */
export const ObservableLike_isEnumerable: unique symbol;
/** @type {unique symbol} */
export const ObservableLike_isRunnable: unique symbol;
/** @type {unique symbol} */
export const SubjectLike_publish: unique symbol;
/** @type {unique symbol} */
export const ThrottleMode_first: unique symbol;
/** @type {unique symbol} */
export const ThrottleMode_last: unique symbol;
/** @type {unique symbol} */
export const ThrottleMode_interval: unique symbol;
