/** @type {unique symbol} */
export const SchedulerLike_inContinuation: unique symbol;
/** @type {unique symbol} */
export const SchedulerLike_now: unique symbol;
/** @type {unique symbol} */
export const SchedulerLike_requestYield: unique symbol;
/** @type {unique symbol} */
export const SchedulerLike_shouldYield: unique symbol;
/** @type {unique symbol} */
export const SchedulerLike_schedule: unique symbol;
/** @type {unique symbol} */
export const ContinuationContextLike_yield: unique symbol;
/** @type {unique symbol} */
export const PauseableSchedulerLike_isPaused: unique symbol;
/** @type {unique symbol} */
export const PauseableSchedulerLike_pause: unique symbol;
/** @type {unique symbol} */
export const PauseableSchedulerLike_resume: unique symbol;
/** @type {unique symbol} */
export const VirtualTimeSchedulerLike_run: unique symbol;
