/** @type {unique symbol} */
export const __AssociativeCollectionLike_keys: unique symbol;
/** @type {unique symbol} */
export const __QueueableLike_capacity: unique symbol;
/** @type {unique symbol} */
export const __CollectionLike_count: unique symbol;
/** @type {unique symbol} */
export const __Container_T: unique symbol;
/** @type {unique symbol} */
export const __Container_type: unique symbol;
/** @type {unique symbol} */
export const __DispatcherLike_complete: unique symbol;
/** @type {unique symbol} */
export const __DispatcherLikeEvent_capacityExceeded: unique symbol;
/** @type {unique symbol} */
export const __DispatcherLikeEvent_completed: unique symbol;
/** @type {unique symbol} */
export const __DispatcherLikeEvent_ready: unique symbol;
/** @type {unique symbol} */
export const __DisposableLike_add: unique symbol;
/** @type {unique symbol} */
export const __DisposableLike_dispose: unique symbol;
/** @type {unique symbol} */
export const __DisposableLike_error: unique symbol;
/** @type {unique symbol} */
export const __DisposableLike_isDisposed: unique symbol;
/** @type {unique symbol} */
export const __EnumerableLike_enumerate: unique symbol;
/** @type {unique symbol} */
export const __EnumeratorLike_isCompleted: unique symbol;
/** @type {unique symbol} */
export const __EnumeratorLike_move: unique symbol;
/** @type {unique symbol} */
export const __EnumeratorLike_current: unique symbol;
/** @type {unique symbol} */
export const __EnumeratorLike_hasCurrent: unique symbol;
/** @type {unique symbol} */
export const __EventSourceLike_addEventListener: unique symbol;
/** @type {unique symbol} */
export const __EventListenerLike_isErrorSafe: unique symbol;
/** @type {unique symbol} */
export const __EventPublisherLike_listenerCount: unique symbol;
/** @type {unique symbol} */
export const __KeyedCollectionLike_get: unique symbol;
/** @type {unique symbol} */
export const __Container_TKey: unique symbol;
/** @type {unique symbol} */
export const __ObservableLike_observe: unique symbol;
/** @type {unique symbol} */
export const __ObservableLike_isDeferred: unique symbol;
/** @type {unique symbol} */
export const __ObservableLike_isEnumerable: unique symbol;
/** @type {unique symbol} */
export const __ObservableLike_isPure: unique symbol;
/** @type {unique symbol} */
export const __ObservableLike_isRunnable: unique symbol;
/** @type {unique symbol} */
export const __PauseableLike_isPaused: unique symbol;
/** @type {unique symbol} */
export const __PauseableLike_pause: unique symbol;
/** @type {unique symbol} */
export const __PauseableLike_resume: unique symbol;
/** @type {unique symbol} */
export const __PublisherLike_observerCount: unique symbol;
/** @type {unique symbol} */
export const __QueueableLike_enqueue: unique symbol;
/** @type {unique symbol} */
export const __QueueableLike_backpressureStrategy: unique symbol;
/** @type {unique symbol} */
export const __ReplayObservableLike_buffer: unique symbol;
/** @type {unique symbol} */
export const __SchedulerLike_inContinuation: unique symbol;
/** @type {unique symbol} */
export const __SchedulerLike_maxYieldInterval: unique symbol;
/** @type {unique symbol} */
export const __SchedulerLike_now: unique symbol;
/** @type {unique symbol} */
export const __SchedulerLike_requestYield: unique symbol;
/** @type {unique symbol} */
export const __SchedulerLike_schedule: unique symbol;
/** @type {unique symbol} */
export const __SchedulerLike_shouldYield: unique symbol;
/** @type {unique symbol} */
export const __SchedulerLike_yield: unique symbol;
/** @type {unique symbol} */
export const __SinkLike_notify: unique symbol;
/** @type {unique symbol} */
export const __StoreLike_value: unique symbol;
/** @type {unique symbol} */
export const __StreamLike_scheduler: unique symbol;
/** @type {unique symbol} */
export const __StreamableLike_stream: unique symbol;
/** @type {unique symbol} */
export const __StreamableLike_TStream: unique symbol;
/** @type {unique symbol} */
export const __VirtualTimeSchedulerLike_run: unique symbol;
/** @type {unique symbol} */
export const __WindowLocationLike_push: unique symbol;
/** @type {unique symbol} */
export const __WindowLocationLike_goBack: unique symbol;
/** @type {unique symbol} */
export const __WindowLocationLike_canGoBack: unique symbol;
/** @type {unique symbol} */
export const __WindowLocationLike_replace: unique symbol;
/** @type {unique symbol} */
export const __ContinuationLike_activeChild: unique symbol;
/** @type {unique symbol} */
export const __ContinuationLike_run: unique symbol;
/** @type {unique symbol} */
export const __ContinuationLike_parent: unique symbol;
/** @type {unique symbol} */
export const __ContinuationLike_scheduler: unique symbol;
/** @type {unique symbol} */
export const __ContinuationSchedulerLike_schedule: unique symbol;
/** @type {unique symbol} */
export const __DelegatingLike_delegate: unique symbol;
/** @type {unique symbol} */
export const __MutableEnumeratorLike_reset: unique symbol;
/** @type {unique symbol} */
export const __MutableKeyedCollectionLike_set: unique symbol;
/** @type {unique symbol} */
export const __QueueLike_head: unique symbol;
/** @type {unique symbol} */
export const __QueueLike_dequeue: unique symbol;
/** @type {unique symbol} */
export const __SchedulerImplementationLike_runContinuation: unique symbol;
/** @type {unique symbol} */
export const __SchedulerImplementationLike_scheduleContinuation: unique symbol;
/** @type {unique symbol} */
export const __SchedulerImplementationLike_shouldYield: unique symbol;
/** @type {unique symbol} */
export const __SerialDisposableLike_current: unique symbol;
/** @type {unique symbol} */
export const __StackLike_pop: unique symbol;
/** @type {unique symbol} */
export const __StackLike_head: unique symbol;
/** @type {unique symbol} */
export const __DelegatingDispatcherMixin_delegate: unique symbol;
/** @type {unique symbol} */
export const __DelegatingDisposableMixin_delegate: unique symbol;
/** @type {unique symbol} */
export const __DelegatingReplayObservableMixin_delegate: unique symbol;
/** @type {unique symbol} */
export const __DelegatingQueueableMixin_delegate: unique symbol;
/** @type {unique symbol} */
export const __DelegatingSchedulerImplementationMixin_delegate: unique symbol;
/** @type {unique symbol} */
export const __DisposableMixin_disposables: unique symbol;
/** @type {unique symbol} */
export const __DistinctUntilChangedLike_equality: unique symbol;
/** @type {unique symbol} */
export const __DistinctUntilChangedLike_prev: unique symbol;
/** @type {unique symbol} */
export const __DistinctUntilChangedLike_hasValue: unique symbol;
/** @type {unique symbol} */
export const __IndexedQueueMixin_head: unique symbol;
/** @type {unique symbol} */
export const __IndexedQueueMixin_tail: unique symbol;
/** @type {unique symbol} */
export const __IndexedQueueMixin_capacityMask: unique symbol;
/** @type {unique symbol} */
export const __IndexedQueueMixin_values: unique symbol;
/** @type {unique symbol} */
export const __LazyInitEventMixin_eventPublisher: unique symbol;
/** @type {unique symbol} */
export const __ObserverMixin_dispatchSubscription: unique symbol;
/** @type {unique symbol} */
export const __ObserverMixin_isCompleted: unique symbol;
/** @type {unique symbol} */
export const __SchedulerImplementationMixin_currentContinuation: unique symbol;
/** @type {unique symbol} */
export const __SchedulerImplementationMixin_startTime: unique symbol;
/** @type {unique symbol} */
export const __SchedulerImplementationMixin_yieldRequested: unique symbol;
/** @type {unique symbol} */
export const __SerialDisposableMixin_current: unique symbol;
/** @type {unique symbol} */
export const __BufferingLike_buffer: unique symbol;
/** @type {unique symbol} */
export const __BufferingLike_count: unique symbol;
/** @type {unique symbol} */
export const __CountingLike_count: unique symbol;
/** @type {unique symbol} */
export const __DecodeWithCharsetLike_textDecoder: unique symbol;
/** @type {unique symbol} */
export const __ForEachLike_effect: unique symbol;
/** @type {unique symbol} */
export const __HigherOrderEnumerator_inner: unique symbol;
/** @type {unique symbol} */
export const __LiftedLike_source: unique symbol;
/** @type {unique symbol} */
export const __LiftedLike_operators: unique symbol;
/** @type {unique symbol} */
export const __MappingLike_selector: unique symbol;
/** @type {unique symbol} */
export const __PairwiseLike_prev: unique symbol;
/** @type {unique symbol} */
export const __PairwiseLike_hasPrev: unique symbol;
/** @type {unique symbol} */
export const __PredicatedLike_predicate: unique symbol;
/** @type {unique symbol} */
export const __ReducerAccumulatorLike_acc: unique symbol;
/** @type {unique symbol} */
export const __ReducerAccumulatorLike_reducer: unique symbol;
/** @type {unique symbol} */
export const __SchedulerTaskLike_continuation: unique symbol;
/** @type {unique symbol} */
export const __SchedulerTaskLike_dueTime: unique symbol;
/** @type {unique symbol} */
export const __SchedulerTaskLike_id: unique symbol;
/** @type {unique symbol} */
export const __TakeLastLike_queue: unique symbol;
/** @type {unique symbol} */
export const __TakeWhileLike_inclusive: unique symbol;
/** @type {unique symbol} */
export const __WithLatestLike_hasLatest: unique symbol;
/** @type {unique symbol} */
export const __WithLatestLike_otherLatest: unique symbol;
/** @type {unique symbol} */
export const __WithLatestLike_selector: unique symbol;
/** @type {unique symbol} */
export const __ZipLike_enumerators: unique symbol;
/** @type {unique symbol} */
export const __AwaitOrObserveEffect_observable: unique symbol;
/** @type {unique symbol} */
export const __AwaitOrObserveEffect_subscription: unique symbol;
/** @type {unique symbol} */
export const __AwaitOrObserveEffect_value: unique symbol;
/** @type {unique symbol} */
export const __AwaitOrObserveEffect_hasValue: unique symbol;
/** @type {unique symbol} */
export const __BufferObserver_durationFunction: unique symbol;
/** @type {unique symbol} */
export const __BufferObserver_durationSubscription: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_index: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_cleanup: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_observableConfig: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_effects: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_mode: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_observer: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_runComputation: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_scheduledComputationSubscription: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_awaitOrObserve: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_constant: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_memoOrUse: unique symbol;
/** @type {unique symbol} */
export const __ComputeEffect_type: unique symbol;
/** @type {unique symbol} */
export const __ConstantEffect_args: unique symbol;
/** @type {unique symbol} */
export const __ConstantEffect_value: unique symbol;
/** @type {unique symbol} */
export const __Continuation_effect: unique symbol;
/** @type {unique symbol} */
export const __CreateEventSource_createDelegate: unique symbol;
/** @type {unique symbol} */
export const __CreateObservable_effect: unique symbol;
/** @type {unique symbol} */
export const __DispatchedObservable_dispatcher: unique symbol;
/** @type {unique symbol} */
export const __EnqueueObserver_queue: unique symbol;
/** @type {unique symbol} */
export const __Enumerator_private_current: unique symbol;
/** @type {unique symbol} */
export const __EventPublisher_listeners: unique symbol;
/** @type {unique symbol} */
export const __HigherOrderObservable_currentRef: unique symbol;
/** @type {unique symbol} */
export const __IteratorEnumerator_iterator: unique symbol;
/** @type {unique symbol} */
export const __LatestCtx_delegate: unique symbol;
/** @type {unique symbol} */
export const __LatestCtx_mode: unique symbol;
/** @type {unique symbol} */
export const __LatestCtx_completedCount: unique symbol;
/** @type {unique symbol} */
export const __LatestCtx_observers: unique symbol;
/** @type {unique symbol} */
export const __LatestObserver_ready: unique symbol;
/** @type {unique symbol} */
export const __LatestObserver_latest: unique symbol;
/** @type {unique symbol} */
export const __LatestObserver_ctx: unique symbol;
/** @type {unique symbol} */
export const __LiftedEnumerable_ops: unique symbol;
/** @type {unique symbol} */
export const __MemoOrUsingEffect_func: unique symbol;
/** @type {unique symbol} */
export const __MemoOrUsingEffect_args: unique symbol;
/** @type {unique symbol} */
export const __MemoOrUsingEffect_value: unique symbol;
/** @type {unique symbol} */
export const __MergeAllObserver_activeCount: unique symbol;
/** @type {unique symbol} */
export const __MergeAllObserver_concurrency: unique symbol;
/** @type {unique symbol} */
export const __MergeAllObserver_onDispose: unique symbol;
/** @type {unique symbol} */
export const __MergeAllObserver_observablesQueue: unique symbol;
/** @type {unique symbol} */
export const __Object_init: unique symbol;
/** @type {unique symbol} */
export const __Object_properties: unique symbol;
/** @type {unique symbol} */
export const __Object_prototype: unique symbol;
/** @type {unique symbol} */
export const __Object_private_initializedProperties: unique symbol;
/** @type {unique symbol} */
export const __PauseableScheduler_delayed: unique symbol;
/** @type {unique symbol} */
export const __PauseableScheduler_dueTime: unique symbol;
/** @type {unique symbol} */
export const __PauseableScheduler_hostContinuation: unique symbol;
/** @type {unique symbol} */
export const __PauseableScheduler_hostScheduler: unique symbol;
/** @type {unique symbol} */
export const __PauseableScheduler_queue: unique symbol;
/** @type {unique symbol} */
export const __PauseableScheduler_initialTime: unique symbol;
/** @type {unique symbol} */
export const __PauseableScheduler_resumedTime: unique symbol;
/** @type {unique symbol} */
export const __PauseableScheduler_taskIDCounter: unique symbol;
/** @type {unique symbol} */
export const __PriorityQueueImpl_comparator: unique symbol;
/** @type {unique symbol} */
export const __Publisher_observers: unique symbol;
/** @type {unique symbol} */
export const __ThrottleObserver_value: unique symbol;
/** @type {unique symbol} */
export const __ThrottleObserver_hasValue: unique symbol;
/** @type {unique symbol} */
export const __ThrottleObserver_durationSubscription: unique symbol;
/** @type {unique symbol} */
export const __ThrottleObserver_durationFunction: unique symbol;
/** @type {unique symbol} */
export const __ThrottleObserver_mode: unique symbol;
/** @type {unique symbol} */
export const __ThrottleObserver_onNotify: unique symbol;
/** @type {unique symbol} */
export const __ThrowIfEmptyObserver_isEmpty: unique symbol;
/** @type {unique symbol} */
export const __TimeoutObserver_duration: unique symbol;
/** @type {unique symbol} */
export const __VirtualTimeScheduler_maxMicroTaskTicks: unique symbol;
/** @type {unique symbol} */
export const __VirtualTimeScheduler_microTaskTicks: unique symbol;
/** @type {unique symbol} */
export const __VirtualTimeScheduler_taskIDCount: unique symbol;
/** @type {unique symbol} */
export const __WindowLocationStream_historyCounter: unique symbol;
/** @type {unique symbol} */
export const __WithCurrentTimeObserver_selector: unique symbol;
/** @type {unique symbol} */
export const __ZipObserver_queuedEnumerator: unique symbol;
/** @type {unique symbol} */
export const __ZipWithLatestFromObserver_TAQueue: unique symbol;
