/** @type {unique symbol} */
export const __BufferLike_capacity: unique symbol;
/** @type {unique symbol} */
export const __CollectionLike_count: unique symbol;
/** @type {unique symbol} */
export const __ContainerLike_T: unique symbol;
/** @type {unique symbol} */
export const __ContainerLike_type: unique symbol;
/** @type {unique symbol} */
export const __ContinuationContextLike_yield: unique symbol;
/** @type {unique symbol} */
export const __DispatcherLike_complete: unique symbol;
/** @type {unique symbol} */
export const __DisposableLike_add: unique symbol;
/** @type {unique symbol} */
export const __DisposableLike_dispose: unique symbol;
/** @type {unique symbol} */
export const __DisposableLike_error: unique symbol;
/** @type {unique symbol} */
export const __DisposableLike_isDisposed: unique symbol;
/** @type {unique symbol} */
export const __EnumeratorLike_move: unique symbol;
/** @type {unique symbol} */
export const __EnumeratorLike_current: unique symbol;
/** @type {unique symbol} */
export const __EnumeratorLike_hasCurrent: unique symbol;
/** @type {unique symbol} */
export const __EventListenerLike_notify: unique symbol;
/** @type {unique symbol} */
export const __EventSourceLike_addListener: unique symbol;
/** @type {unique symbol} */
export const __EventSourceLike_listenerCount: unique symbol;
/** @type {unique symbol} */
export const __FlowableStreamLike_isPaused: unique symbol;
/** @type {unique symbol} */
export const __FlowableStreamLike_pause: unique symbol;
/** @type {unique symbol} */
export const __FlowableStreamLike_resume: unique symbol;
/** @type {unique symbol} */
export const __KeyedCollectionLike_get: unique symbol;
/** @type {unique symbol} */
export const __KeyedContainerLike_TKey: unique symbol;
/** @type {unique symbol} */
export const __MulticastObservableLike_observerCount: unique symbol;
/** @type {unique symbol} */
export const __ObserverLike_notify: unique symbol;
/** @type {unique symbol} */
export const __ObservableLike_observe: unique symbol;
/** @type {unique symbol} */
export const __ObservableLike_isEnumerable: unique symbol;
/** @type {unique symbol} */
export const __ObservableLike_isRunnable: unique symbol;
/** @type {unique symbol} */
export const __PauseableSchedulerLike_isPaused: unique symbol;
/** @type {unique symbol} */
export const __PauseableSchedulerLike_pause: unique symbol;
/** @type {unique symbol} */
export const __PauseableSchedulerLike_resume: unique symbol;
/** @type {unique symbol} */
export const __QueueableLike_enqueue: unique symbol;
/** @type {unique symbol} */
export const __QueueableLike_backpressureStrategy: unique symbol;
/** @type {unique symbol} */
export const __ReplayableLike_buffer: unique symbol;
/** @type {unique symbol} */
export const __SchedulerLike_inContinuation: unique symbol;
/** @type {unique symbol} */
export const __SchedulerLike_maxYieldInterval: unique symbol;
/** @type {unique symbol} */
export const __SchedulerLike_now: unique symbol;
/** @type {unique symbol} */
export const __SchedulerLike_requestYield: unique symbol;
/** @type {unique symbol} */
export const __SchedulerLike_schedule: unique symbol;
/** @type {unique symbol} */
export const __SchedulerLike_shouldYield: unique symbol;
/** @type {unique symbol} */
export const __StreamLike_scheduler: unique symbol;
/** @type {unique symbol} */
export const __StreamableLike_stream: unique symbol;
/** @type {unique symbol} */
export const __StreamableLike_isEnumerable: unique symbol;
/** @type {unique symbol} */
export const __StreamableLike_isInteractive: unique symbol;
/** @type {unique symbol} */
export const __StreamableLike_isRunnable: unique symbol;
/** @type {unique symbol} */
export const __VirtualTimeSchedulerLike_run: unique symbol;
/** @type {unique symbol} */
export const __WindowLocationStreamLike_goBack: unique symbol;
/** @type {unique symbol} */
export const __WindowLocationStreamLike_canGoBack: unique symbol;
/** @type {unique symbol} */
export const __WindowLocationStream_historyCounter: unique symbol;
/** @type {unique symbol} */
export const __WindowLocationStreamLike_replace: unique symbol;
/** @type {unique symbol} */
export const __ContinuationLike_run: unique symbol;
/** @type {unique symbol} */
export const __ContinuationLike_priority: unique symbol;
/** @type {unique symbol} */
export const __ContinuationLike_continuationScheduler: unique symbol;
/** @type {unique symbol} */
export const __ContinuationSchedulerLike_schedule: unique symbol;
/** @type {unique symbol} */
export const __ContinuationSchedulerLike_shouldYield: unique symbol;
/** @type {unique symbol} */
export const __DelegatingLike_delegate: unique symbol;
/** @type {unique symbol} */
export const __MutableEnumeratorLike_reset: unique symbol;
/** @type {unique symbol} */
export const __MutableKeyedCollectionLike_set: unique symbol;
/** @type {unique symbol} */
export const __PrioritySchedulerImplementationLike_runContinuation: unique symbol;
/** @type {unique symbol} */
export const __PrioritySchedulerImplementationLike_shouldYield: unique symbol;
/** @type {unique symbol} */
export const __QueueLike_head: unique symbol;
/** @type {unique symbol} */
export const __QueueLike_dequeue: unique symbol;
/** @type {unique symbol} */
export const __SerialDisposableLike_current: unique symbol;
/** @type {unique symbol} */
export const __StackLike_pop: unique symbol;
/** @type {unique symbol} */
export const __StackLike_head: unique symbol;
/** @type {unique symbol} */
export const __DelegatingDispatcherMixin_delegate: unique symbol;
/** @type {unique symbol} */
export const __DelegatingDisposableMixin_delegate: unique symbol;
/** @type {unique symbol} */
export const __DelegatingMulticastObservableMixin_delegate: unique symbol;
/** @type {unique symbol} */
export const __DelegatingQueueableMixin_delegate: unique symbol;
/** @type {unique symbol} */
export const __DelegatingSchedulerMixin_delegate: unique symbol;
/** @type {unique symbol} */
export const __DelegatingStreamMixin_delegate: unique symbol;
/** @type {unique symbol} */
export const __AnimationFrameScheduler_delayScheduler: unique symbol;
/** @type {unique symbol} */
export const __AwaitOrObserveEffect_observable: unique symbol;
/** @type {unique symbol} */
export const __AwaitOrObserveEffect_subscription: unique symbol;
/** @type {unique symbol} */
export const __AwaitOrObserveEffect_value: unique symbol;
/** @type {unique symbol} */
export const __AwaitOrObserveEffect_hasValue: unique symbol;
/** @type {unique symbol} */
export const __BufferObserver_buffer: unique symbol;
/** @type {unique symbol} */
export const __BufferObserver_durationFunction: unique symbol;
/** @type {unique symbol} */
export const __BufferObserver_durationSubscription: unique symbol;
/** @type {unique symbol} */
export const __BufferObserver_count: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_index: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_cleanup: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_observableConfig: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_effects: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_mode: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_observer: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_runComputation: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_scheduledComputationSubscription: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_awaitOrObserve: unique symbol;
/** @type {unique symbol} */
export const __ComputeContext_memoOrUse: unique symbol;
/** @type {unique symbol} */
export const __ComputeEffect_type: unique symbol;
/** @type {unique symbol} */
export const __Continuation_childContinuation: unique symbol;
/** @type {unique symbol} */
export const __Continuation_effect: unique symbol;
/** @type {unique symbol} */
export const __CreateObservable_effect: unique symbol;
/** @type {unique symbol} */
export const __DecodeWithCharsetObserver_textDecoder: unique symbol;
/** @type {unique symbol} */
export const __DispatchedObservable_observer: unique symbol;
/** @type {unique symbol} */
export const __DisposableMixin_disposables: unique symbol;
/** @type {unique symbol} */
export const __DistinctUntilChangedObserver_equality: unique symbol;
/** @type {unique symbol} */
export const __DistinctUntilChangedObserver_prev: unique symbol;
/** @type {unique symbol} */
export const __DistinctUntilChangedObserver_hasValue: unique symbol;
/** @type {unique symbol} */
export const __EnqueueObserver_effect: unique symbol;
/** @type {unique symbol} */
export const __Enumerator_private_current: unique symbol;
/** @type {unique symbol} */
export const __EnumerableEnumerator_continuationQueue: unique symbol;
/** @type {unique symbol} */
export const __FifoQueue_head: unique symbol;
/** @type {unique symbol} */
export const __FifoQueue_tail: unique symbol;
/** @type {unique symbol} */
export const __FifoQueue_capacityMask: unique symbol;
/** @type {unique symbol} */
export const __FifoQueue_values: unique symbol;
/** @type {unique symbol} */
export const __HigherOrderObservable_currentRef: unique symbol;
/** @type {unique symbol} */
export const __IteratorEnumerator_iterator: unique symbol;
/** @type {unique symbol} */
export const __KeepObserver_predicate: unique symbol;
/** @type {unique symbol} */
export const __LatestCtx_delegate: unique symbol;
/** @type {unique symbol} */
export const __LatestCtx_mode: unique symbol;
/** @type {unique symbol} */
export const __LatestCtx_completedCount: unique symbol;
/** @type {unique symbol} */
export const __LatestCtx_observers: unique symbol;
/** @type {unique symbol} */
export const __LatestObserver_ready: unique symbol;
/** @type {unique symbol} */
export const __LatestObserver_latest: unique symbol;
/** @type {unique symbol} */
export const __LatestObserver_ctx: unique symbol;
/** @type {unique symbol} */
export const __LiftedAsyncEnumerable_src: unique symbol;
/** @type {unique symbol} */
export const __LiftedAsyncEnumerable_operators: unique symbol;
/** @type {unique symbol} */
export const __LiftedObservable_source: unique symbol;
/** @type {unique symbol} */
export const __LiftedObservable_operators: unique symbol;
/** @type {unique symbol} */
export const __MapObserver_mapper: unique symbol;
/** @type {unique symbol} */
export const __MemoOrUsingEffect_func: unique symbol;
/** @type {unique symbol} */
export const __MemoOrUsingEffect_args: unique symbol;
/** @type {unique symbol} */
export const __MemoOrUsingEffect_value: unique symbol;
/** @type {unique symbol} */
export const __MergeAllObserver_activeCount: unique symbol;
/** @type {unique symbol} */
export const __MergeAllObserver_maxConcurrency: unique symbol;
/** @type {unique symbol} */
export const __MergeAllObserver_onDispose: unique symbol;
/** @type {unique symbol} */
export const __MergeAllObserver_observablesQueue: unique symbol;
/** @type {unique symbol} */
export const __MergeObserverCtx_completedCount: unique symbol;
/** @type {unique symbol} */
export const __NODE_JS_PAUSE_EVENT: unique symbol;
/** @type {unique symbol} */
export const __Object_init: unique symbol;
/** @type {unique symbol} */
export const __Object_properties: unique symbol;
/** @type {unique symbol} */
export const __Object_prototype: unique symbol;
/** @type {unique symbol} */
export const __Object_private_initializedProperties: unique symbol;
/** @type {unique symbol} */
export const __ObserverMixin_continuation: unique symbol;
/** @type {unique symbol} */
export const __ObserverMixin_dispatchSubscription: unique symbol;
/** @type {unique symbol} */
export const __ObserverMixin_isCompleted: unique symbol;
/** @type {unique symbol} */
export const __ObserverMixin_scheduler: unique symbol;
/** @type {unique symbol} */
export const __PairwiseObserver_prev: unique symbol;
/** @type {unique symbol} */
export const __PairwiseObserver_hasPrev: unique symbol;
/** @type {unique symbol} */
export const __PriorityQueueImpl_comparator: unique symbol;
/** @type {unique symbol} */
export const __PrioritySchedulerDelegatingScheduler_priorityScheduler: unique symbol;
/** @type {unique symbol} */
export const __PrioritySchedulerDelegatingScheduler_priority: unique symbol;
/** @type {unique symbol} */
export const __Publisher_observers: unique symbol;
/** @type {unique symbol} */
export const __QueueScheduler_delayed: unique symbol;
/** @type {unique symbol} */
export const __QueueScheduler_dueTime: unique symbol;
/** @type {unique symbol} */
export const __QueueScheduler_hostContinuation: unique symbol;
/** @type {unique symbol} */
export const __QueueScheduler_hostScheduler: unique symbol;
/** @type {unique symbol} */
export const __QueueScheduler_queue: unique symbol;
/** @type {unique symbol} */
export const __QueueScheduler_taskIDCounter: unique symbol;
/** @type {unique symbol} */
export const __QueueTask_continuation: unique symbol;
/** @type {unique symbol} */
export const __QueueTask_dueTime: unique symbol;
/** @type {unique symbol} */
export const __QueueTask_priority: unique symbol;
/** @type {unique symbol} */
export const __QueueTask_taskID: unique symbol;
/** @type {unique symbol} */
export const __ReadonlyArrayEnumerator_values: unique symbol;
/** @type {unique symbol} */
export const __ReadonlyArrayEnumerator_index: unique symbol;
/** @type {unique symbol} */
export const __ReadonlyArrayEnumerator_count: unique symbol;
/** @type {unique symbol} */
export const __ReduceObserver_reducer: unique symbol;
/** @type {unique symbol} */
export const __ReduceObserver_acc: unique symbol;
/** @type {unique symbol} */
export const __SatisfyObserver_predicate: unique symbol;
/** @type {unique symbol} */
export const __ScanObserver_reducer: unique symbol;
/** @type {unique symbol} */
export const __ScanObserver_acc: unique symbol;
/** @type {unique symbol} */
export const __SchedulerMixin_yieldRequested: unique symbol;
/** @type {unique symbol} */
export const __SchedulerMixin_currentContinuation: unique symbol;
/** @type {unique symbol} */
export const __SchedulerMixin_startTime: unique symbol;
/** @type {unique symbol} */
export const __SerialDisposableMixin_current: unique symbol;
/** @type {unique symbol} */
export const __SkipFirstObserver_skipCount: unique symbol;
/** @type {unique symbol} */
export const __SkipFirstObserver_count: unique symbol;
/** @type {unique symbol} */
export const __TakeFirstObserver_takeCount: unique symbol;
/** @type {unique symbol} */
export const __TakeFirstObserver_count: unique symbol;
/** @type {unique symbol} */
export const __TakeLastObserver_takeLastQueue: unique symbol;
/** @type {unique symbol} */
export const __TakeWhileObserver_predicate: unique symbol;
/** @type {unique symbol} */
export const __TakeWhileObserver_inclusive: unique symbol;
/** @type {unique symbol} */
export const __ThrottleObserver_value: unique symbol;
/** @type {unique symbol} */
export const __ThrottleObserver_hasValue: unique symbol;
/** @type {unique symbol} */
export const __ThrottleObserver_durationSubscription: unique symbol;
/** @type {unique symbol} */
export const __ThrottleObserver_durationFunction: unique symbol;
/** @type {unique symbol} */
export const __ThrottleObserver_mode: unique symbol;
/** @type {unique symbol} */
export const __ThrottleObserver_onNotify: unique symbol;
/** @type {unique symbol} */
export const __ThrowIfEmptyObserver_isEmpty: unique symbol;
/** @type {unique symbol} */
export const __timeoutError: unique symbol;
/** @type {unique symbol} */
export const __TimeoutObserver_duration: unique symbol;
/** @type {unique symbol} */
export const __VirtualTask_continuation: unique symbol;
/** @type {unique symbol} */
export const __VirtualTask_dueTime: unique symbol;
/** @type {unique symbol} */
export const __VirtualTask_id: unique symbol;
/** @type {unique symbol} */
export const __VirtualTimeScheduler_maxMicroTaskTicks: unique symbol;
/** @type {unique symbol} */
export const __VirtualTimeScheduler_microTaskTicks: unique symbol;
/** @type {unique symbol} */
export const __VirtualTimeScheduler_taskIDCount: unique symbol;
/** @type {unique symbol} */
export const __WithCurrentTimeObserver_selector: unique symbol;
/** @type {unique symbol} */
export const __WithLatestFromObserver_hasLatest: unique symbol;
/** @type {unique symbol} */
export const __WithLatestFromObserver_otherLatest: unique symbol;
/** @type {unique symbol} */
export const __WithLatestFromObserver_selector: unique symbol;
/** @type {unique symbol} */
export const __ZipObserver_enumerators: unique symbol;
/** @type {unique symbol} */
export const __ZipObserver_queuedEnumerator: unique symbol;
/** @type {unique symbol} */
export const __ZipWithLatestFromObserver_hasLatest: unique symbol;
/** @type {unique symbol} */
export const __ZipWithLatestFromObserver_otherLatest: unique symbol;
/** @type {unique symbol} */
export const __ZipWithLatestFromObserver_selector: unique symbol;
/** @type {unique symbol} */
export const __ZipWithLatestFromObserver_TAQueue: unique symbol;
