/** @type {unique symbol} */
export const DisposableLike_add: unique symbol;
/** @type {unique symbol} */
export const DisposableLike_dispose: unique symbol;
/** @type {unique symbol} */
export const DisposableLike_error: unique symbol;
/** @type {unique symbol} */
export const DisposableLike_isDisposed: unique symbol;
/** @type {unique symbol} */
export const QueueableLike_push: unique symbol;
/** @type {unique symbol} */
export const QueueableLike_maxBufferSize: unique symbol;
/** @type {unique symbol} */
export const SerialDisposableLike_current: unique symbol;
/** @type {unique symbol} */
export const QueueLike_head: unique symbol;
/** @type {unique symbol} */
export const QueueLike_pull: unique symbol;
/** @type {unique symbol} */
export const QueueLike_count: unique symbol;
/** @type {unique symbol} */
export const IndexedQueueLike_get: unique symbol;
/** @type {unique symbol} */
export const IndexedQueueLike_set: unique symbol;
/** @type {unique symbol} */
export const IndexedQueueLike_pop: unique symbol;
