/// <reference types="./Enumerable.d.ts" />

import { Container_type, } from "../core.js";
import Container_identity from "../core/Container/__internal__/Container.identity.js";
import Enumerable_catchError from "../core/Enumerable/__internal__/Enumerable.catchError.js";
import Enumerable_concatAll from "../core/Enumerable/__internal__/Enumerable.concatAll.js";
import Enumerable_concatMap from "../core/Enumerable/__internal__/Enumerable.concatMap.js";
import Enumerable_defer from "../core/Enumerable/__internal__/Enumerable.defer.js";
import Enumerable_encodeUtf8 from "../core/Enumerable/__internal__/Enumerable.encodeUtf8.js";
import Enumerable_flatMapIterable from "../core/Enumerable/__internal__/Enumerable.flatMapIterable.js";
import Enumerable_scanLast from "../core/Enumerable/__internal__/Enumerable.scanLast.js";
import Iterable_toObservable from "../core/Iterable/__internal__/Iterable.toObservable.js";
import Observable_buffer from "../core/Observable/__internal__/Observable.buffer.js";
import Observable_concat from "../core/Observable/__internal__/Observable.concat.js";
import Observable_concatWith from "../core/Observable/__internal__/Observable.concatWith.js";
import Observable_decodeWithCharset from "../core/Observable/__internal__/Observable.decodeWithCharset.js";
import Observable_distinctUntilChanged from "../core/Observable/__internal__/Observable.distinctUntilChanged.js";
import Observable_empty from "../core/Observable/__internal__/Observable.empty.js";
import Observable_endWith from "../core/Observable/__internal__/Observable.endWith.js";
import Observable_forEach from "../core/Observable/__internal__/Observable.forEach.js";
import Observable_forkConcat from "../core/Observable/__internal__/Observable.forkConcat.js";
import Observable_forkZip from "../core/Observable/__internal__/Observable.forkZip.js";
import Observable_fromFactory from "../core/Observable/__internal__/Observable.fromFactory.js";
import Observable_generate from "../core/Observable/__internal__/Observable.generate.js";
import Observable_ignoreElements from "../core/Observable/__internal__/Observable.ignoreElements.js";
import Observable_keep from "../core/Observable/__internal__/Observable.keep.js";
import Observable_keepType from "../core/Observable/__internal__/Observable.keepType.js";
import Observable_map from "../core/Observable/__internal__/Observable.map.js";
import Observable_mapTo from "../core/Observable/__internal__/Observable.mapTo.js";
import Observable_pairwise from "../core/Observable/__internal__/Observable.pairwise.js";
import Observable_retry from "../core/Observable/__internal__/Observable.retry.js";
import Observable_scan from "../core/Observable/__internal__/Observable.scan.js";
import Observable_skipFirst from "../core/Observable/__internal__/Observable.skipFirst.js";
import Observable_startWith from "../core/Observable/__internal__/Observable.startWith.js";
import Observable_takeFirst from "../core/Observable/__internal__/Observable.takeFirst.js";
import Observable_takeLast from "../core/Observable/__internal__/Observable.takeLast.js";
import Observable_takeWhile from "../core/Observable/__internal__/Observable.takeWhile.js";
import Observable_throwIfEmpty from "../core/Observable/__internal__/Observable.throwIfEmpty.js";
import Observable_throws from "../core/Observable/__internal__/Observable.throws.js";
import Observable_zip from "../core/Observable/__internal__/Observable.zip.js";
import Observable_zipWith from "../core/Observable/__internal__/Observable.zipWith.js";
import Optional_toObservable from "../core/Optional/__internal__/Optional.toObservable.js";
import ReadonlyArray_toObservable from "../core/ReadonlyArray/__internal__/ReadonlyArray.toObservable.js";
import Runnable_flow from "../core/Runnable/__internal__/Runnable.flow.js";
import Enumerable_enumerate from "./Enumerable/__internal__/Enumerable.enumerate.js";
import Enumerable_toReadonlyArray from "./Enumerable/__internal__/Enumerable.toReadonlyArray.js";
import { Enumerable_compute } from "./Observable/__internal__/Observable.compute.js";
import Observable_firstAsync from "./Observable/__internal__/Observable.firstAsync.js";
import Observable_lastAsync from "./Observable/__internal__/Observable.lastAsync.js";
import Observable_pick from "./Observable/__internal__/Observable.pick.js";
import Observable_repeat from "./Observable/__internal__/Observable.repeat.js";
import Runnable_contains from "./Runnable/__internal__/Runnable.contains.js";
import Runnable_everySatisfy from "./Runnable/__internal__/Runnable.everySatisfy.js";
import Runnable_first from "./Runnable/__internal__/Runnable.first.js";
import Runnable_fromEnumeratorFactory from "./Runnable/__internal__/Runnable.fromEnumeratorFactory.js";
import Runnable_last from "./Runnable/__internal__/Runnable.last.js";
import Runnable_noneSatisfy from "./Runnable/__internal__/Runnable.noneSatisfy.js";
import Runnable_reduce from "./Runnable/__internal__/Runnable.reduce.js";
import Runnable_someSatisfy from "./Runnable/__internal__/Runnable.someSatisfy.js";
export const buffer = Observable_buffer;
export const catchError = Enumerable_catchError;
/**
 * @category Constructor
 */
export const compute = Enumerable_compute;
export const concat = Observable_concat;
export const concatAll = Enumerable_concatAll;
export const concatMap = Enumerable_concatMap;
export const concatWith = Observable_concatWith;
export const contains = Runnable_contains;
export const decodeWithCharset = Observable_decodeWithCharset;
export const defer = Enumerable_defer;
export const distinctUntilChanged = Observable_distinctUntilChanged;
export const empty = Observable_empty;
export const encodeUtf8 = Enumerable_encodeUtf8;
export const endWith = Observable_endWith;
export const enumerate = Enumerable_enumerate;
export const everySatisfy = Runnable_everySatisfy;
export const first = Runnable_first;
// FIXME: use a custom implementation that doesn't schedule
export const firstAsync = Observable_firstAsync;
export const flatMapIterable = Enumerable_flatMapIterable;
export const flow = Runnable_flow;
export const forEach = Observable_forEach;
export const forkConcat = Observable_forkConcat;
export const forkZip = Observable_forkZip;
export const fromEnumeratorFactory = Runnable_fromEnumeratorFactory;
export const fromFactory = Observable_fromFactory;
export const fromIterable = Iterable_toObservable;
export const fromOptional = Optional_toObservable;
export const fromReadonlyArray = ReadonlyArray_toObservable;
export const generate = Observable_generate;
export const identity = Container_identity;
export const ignoreElements = Observable_ignoreElements;
export const keep = Observable_keep;
export const keepType = Observable_keepType;
export const last = Runnable_last;
// FIXME: use a custom implementation that doesn't use a vts
export const lastAsync = Observable_lastAsync;
export const map = Observable_map;
export const mapTo = Observable_mapTo;
export const noneSatisfy = Runnable_noneSatisfy;
export const pairwise = Observable_pairwise;
export const pick = Observable_pick;
export const reduce = Runnable_reduce;
export const repeat = Observable_repeat;
export const retry = Observable_retry;
export const scan = Observable_scan;
export const scanLast = Enumerable_scanLast;
export const skipFirst = Observable_skipFirst;
export const someSatisfy = Runnable_someSatisfy;
export const startWith = Observable_startWith;
export const takeFirst = Observable_takeFirst;
export const takeLast = Observable_takeLast;
export const takeWhile = Observable_takeWhile;
export const throws = Observable_throws;
export const throwIfEmpty = Observable_throwIfEmpty;
export const toReadonlyArray = Enumerable_toReadonlyArray;
export const zip = Observable_zip;
export const zipWith = Observable_zipWith;
