/// <reference types="./Enumerable.d.ts" />

import { Computation_type, } from "../computations.js";
import Enumerable_buffer from "./Enumerable/__internal__/Enumerable.buffer.js";
import Enumerable_concatMany from "./Enumerable/__internal__/Enumerable.concatMany.js";
import Enumerable_decodeWithCharset from "./Enumerable/__internal__/Enumerable.decodeWithCharset.js";
import Enumerable_distinctUntilChanged from "./Enumerable/__internal__/Enumerable.distinctUntilChanged.js";
import Enumerable_empty from "./Enumerable/__internal__/Enumerable.empty.js";
import Enumerable_generate from "./Enumerable/__internal__/Enumerable.generate.js";
import Enumerable_keep from "./Enumerable/__internal__/Enumerable.keep.js";
import Enumerable_map from "./Enumerable/__internal__/Enumerable.map.js";
import Enumerable_pairwise from "./Enumerable/__internal__/Enumerable.pairwise.js";
import Enumerable_range from "./Enumerable/__internal__/Enumerable.range.js";
import Enumerable_reduce from "./Enumerable/__internal__/Enumerable.reduce.js";
import Enumerable_repeat from "./Enumerable/__internal__/Enumerable.repeat.js";
import Enumerable_scan from "./Enumerable/__internal__/Enumerable.scan.js";
import Enumerable_skipFirst from "./Enumerable/__internal__/Enumerable.skipFirst.js";
import Enumerable_takeFirst from "./Enumerable/__internal__/Enumerable.takeFirst.js";
import Enumerable_takeWhile from "./Enumerable/__internal__/Enumerable.takeWhile.js";
import Enumerable_toReadonlyArray from "./Enumerable/__internal__/Enumerable.toReadonlyArray.js";
import Enumerable_zip from "./Enumerable/__internal__/Enumerable.zip.js";
import Enumerable_zipWith from "./Enumerable/__internal__/Enumerable.zipWith.js";
export const buffer = Enumerable_buffer;
export const concatMany = Enumerable_concatMany;
export const decodeWithCharset = Enumerable_decodeWithCharset;
export const distinctUntilChanged = Enumerable_distinctUntilChanged;
export const empty = Enumerable_empty;
export const generate = Enumerable_generate;
export const keep = Enumerable_keep;
export const map = Enumerable_map;
export const pairwise = Enumerable_pairwise;
export const range = Enumerable_range;
export const reduce = Enumerable_reduce;
export const repeat = Enumerable_repeat;
export const scan = Enumerable_scan;
export const skipFirst = Enumerable_skipFirst;
export const takeFirst = Enumerable_takeFirst;
export const takeWhile = Enumerable_takeWhile;
export const toReadonlyArray = Enumerable_toReadonlyArray;
export const zip = Enumerable_zip;
export const zipWith = Enumerable_zipWith;
