/// <reference types="./Disposable.d.ts" />

import Disposable_add from "./Disposable/__internal__/Disposable.add.js";
import Disposable_addTo from "./Disposable/__internal__/Disposable.addTo.js";
import Disposable_bindTo from "./Disposable/__internal__/Disposable.bindTo.js";
import Disposable_create from "./Disposable/__internal__/Disposable.create.js";
import Disposable_disposed from "./Disposable/__internal__/Disposable.disposed.js";
import Disposable_onComplete from "./Disposable/__internal__/Disposable.onComplete.js";
import Disposable_onDisposed from "./Disposable/__internal__/Disposable.onDisposed.js";
import Disposable_onError from "./Disposable/__internal__/Disposable.onError.js";
import Disposable_raiseIfDisposedWithError from "./Disposable/__internal__/Disposable.raiseIfDisposedWithError.js";
import Disposable_toAbortSignal from "./Disposable/__internal__/Disposable.toAbortSignal.js";
import Disposable_toErrorHandler from "./Disposable/__internal__/Disposable.toErrorHandler.js";
import Disposable_using from "./Disposable/__internal__/Disposable.using.js";
import Disposable_usingAsync from "./Disposable/__internal__/Disposable.usingAsync.js";
import Disposable_usingAsyncLazy from "./Disposable/__internal__/Disposable.usingAsyncLazy.js";
import Disposable_usingLazy from "./Disposable/__internal__/Disposable.usingLazy.js";
export const add = Disposable_add;
export const addTo = Disposable_addTo;
export const bindTo = Disposable_bindTo;
export const create = Disposable_create;
export const disposed = Disposable_disposed;
export const onComplete = Disposable_onComplete;
export const onDisposed = Disposable_onDisposed;
export const onError = Disposable_onError;
export const raiseIfDisposedWithError = Disposable_raiseIfDisposedWithError;
export const toAbortSignal = Disposable_toAbortSignal;
export const toErrorHandler = Disposable_toErrorHandler;
export const using = Disposable_using;
export const usingAsync = Disposable_usingAsync;
export const usingAsyncLazy = Disposable_usingAsyncLazy;
export const usingLazy = Disposable_usingLazy;
