import {
  bufferTests,
  concatAllTests,
  concatMapTests,
  concatTests,
  concatWithTests,
  concatYieldMapTests,
  distinctUntilChangedTests,
  endWithTests,
  forEachTests,
  fromReadonlyArrayTests,
  ignoreElementsTests,
  keepTests,
  mapTests,
  mapToTests,
  pairwiseTests,
  repeatTests,
  scanTests,
  skipFirstTests,
  startWithTests,
  takeFirstTests,
  takeLastTests,
  takeWhileTests,
  throwIfEmptyTests,
  toEnumerableObservableTests,
  toEnumerableTests,
  toObservableTests,
  toRunnableObservableTests,
  zipTests,
  zipWithTests,
} from "../../__tests__/operators.js";
import { testModule } from "../../__tests__/testing.js";
import { EnumerableLike } from "../../ix.js";
import * as Enumerable from "../Enumerable.js";

testModule(
  "Enumerable",
  bufferTests(Enumerable),
  concatTests<EnumerableLike>(Enumerable),
  concatAllTests(Enumerable),
  concatMapTests(Enumerable),
  concatWithTests<EnumerableLike>(Enumerable),
  distinctUntilChangedTests(Enumerable),
  endWithTests<EnumerableLike>(Enumerable),
  forEachTests(Enumerable),
  fromReadonlyArrayTests<EnumerableLike>(Enumerable),
  concatYieldMapTests(Enumerable),
  ignoreElementsTests(Enumerable),
  keepTests(Enumerable),
  mapTests(Enumerable),
  mapToTests(Enumerable),
  pairwiseTests(Enumerable),
  repeatTests(Enumerable),
  scanTests(Enumerable),
  skipFirstTests(Enumerable),
  startWithTests<EnumerableLike>(Enumerable),
  takeFirstTests(Enumerable),
  takeLastTests(Enumerable),
  takeWhileTests(Enumerable),
  throwIfEmptyTests(Enumerable),
  toEnumerableTests<EnumerableLike>(Enumerable),
  toEnumerableObservableTests<EnumerableLike>(Enumerable),
  toRunnableObservableTests<EnumerableLike>(Enumerable),
  toObservableTests<EnumerableLike>(Enumerable),
  zipTests<EnumerableLike>(Enumerable),
  zipWithTests<EnumerableLike>(Enumerable),
);
