/// <reference types="./EventSource.d.ts" />

import { Computation_type, } from "../computations.js";
import EventSource_addEventHandler from "./EventSource/__internal__/EventSource.addEventHandler.js";
import EventSource_buffer from "./EventSource/__internal__/EventSource.buffer.js";
import EventSource_create from "./EventSource/__internal__/EventSource.create.js";
import EventSource_decodeWithCharset from "./EventSource/__internal__/EventSource.decodeWithCharset.js";
import EventSource_distinctUntilChanged from "./EventSource/__internal__/EventSource.distinctUntilChanged.js";
import EventSource_fromIterable from "./EventSource/__internal__/EventSource.fromIterable.js";
import EventSource_fromPromise from "./EventSource/__internal__/EventSource.fromPromise.js";
import EventSource_keep from "./EventSource/__internal__/EventSource.keep.js";
import EventSource_map from "./EventSource/__internal__/EventSource.map.js";
import EventSource_merge from "./EventSource/__internal__/EventSource.merge.js";
import EventSource_mergeMany from "./EventSource/__internal__/EventSource.mergeMany.js";
import EventSource_mergeWith from "./EventSource/__internal__/EventSource.mergeWith.js";
import EventSource_pairwise from "./EventSource/__internal__/EventSource.pairwise.js";
import EventSource_scan from "./EventSource/__internal__/EventSource.scan.js";
import EventSource_skipFirst from "./EventSource/__internal__/EventSource.skipFirst.js";
import EventSource_takeFirst from "./EventSource/__internal__/EventSource.takeFirst.js";
import EventSource_takeWhile from "./EventSource/__internal__/EventSource.takeWhile.js";
import EventSource_toReadonlyArrayAsync from "./EventSource/__internal__/EventSource.toReadonlyArrayAsync.js";
export const addEventHandler = EventSource_addEventHandler;
export const buffer = EventSource_buffer;
export const create = EventSource_create;
export const decodeWithCharset = EventSource_decodeWithCharset;
export const distinctUntilChanged = EventSource_distinctUntilChanged;
export const fromIterable = EventSource_fromIterable;
export const fromPromise = EventSource_fromPromise;
export const fromReadonlyArray = EventSource_fromIterable;
export const keep = EventSource_keep;
export const map = EventSource_map;
export const merge = EventSource_merge;
export const mergeMany = EventSource_mergeMany;
export const mergeWith = EventSource_mergeWith;
export const pairwise = EventSource_pairwise;
export const scan = EventSource_scan;
export const skipFirst = EventSource_skipFirst;
export const takeFirst = EventSource_takeFirst;
export const takeWhile = EventSource_takeWhile;
export const toReadonlyArrayAsync = EventSource_toReadonlyArrayAsync;
