/// <reference types="./DeferredObservable.d.ts" />

import DeferredObservable_catchError from "./DeferredObservable/__internal__/DeferredObservable.catchError.js";
import DeferredObservable_concatAll from "./DeferredObservable/__internal__/DeferredObservable.concatAll.js";
import DeferredObservable_concatMap from "./DeferredObservable/__internal__/DeferredObservable.concatMap.js";
import DeferredObservable_exhaust from "./DeferredObservable/__internal__/DeferredObservable.exhaust.js";
import DeferredObservable_exhaustMap from "./DeferredObservable/__internal__/DeferredObservable.exhaustMap.js";
import DeferredObservable_mergeAll from "./DeferredObservable/__internal__/DeferredObservable.mergeAll.js";
import DeferredObservable_mergeMap from "./DeferredObservable/__internal__/DeferredObservable.mergeMap.js";
import DeferredObservable_multicast from "./DeferredObservable/__internal__/DeferredObservable.multicast.js";
import DeferredObservable_repeat from "./DeferredObservable/__internal__/DeferredObservable.repeat.js";
import DeferredObservable_retry from "./DeferredObservable/__internal__/DeferredObservable.retry.js";
import DeferredObservable_scanLast from "./DeferredObservable/__internal__/DeferredObservable.scanLast.js";
import DeferredObservable_scanMany from "./DeferredObservable/__internal__/DeferredObservable.scanMany.js";
import DeferredObservable_share from "./DeferredObservable/__internal__/DeferredObservable.share.js";
import DeferredObservable_switchAll from "./DeferredObservable/__internal__/DeferredObservable.switchAll.js";
import DeferredObservable_switchMap from "./DeferredObservable/__internal__/DeferredObservable.switchMap.js";
import { DeferredObservable_compute } from "./Observable/__internal__/Observable.compute.js";
import { identityLazy } from "./functions.js";
import { Container_type, } from "./types.js";
export const catchError = DeferredObservable_catchError;
export const compute = DeferredObservable_compute;
export const concatAll = DeferredObservable_concatAll;
export const concatMap = DeferredObservable_concatMap;
export const exhaust = DeferredObservable_exhaust;
export const exhaustMap = DeferredObservable_exhaustMap;
export const mergeAll = DeferredObservable_mergeAll;
export const mergeMap = DeferredObservable_mergeMap;
export const multicast = DeferredObservable_multicast;
export const repeat = DeferredObservable_repeat;
export const retry = DeferredObservable_retry;
export const scanLast = DeferredObservable_scanLast;
export const scanMany = DeferredObservable_scanMany;
export const share = DeferredObservable_share;
export const switchAll = DeferredObservable_switchAll;
export const switchMap = DeferredObservable_switchMap;
export const toObservable = identityLazy;
