/// <reference types="./EventSource.d.ts" />

import EventSource_addEventHandler from "./EventSource/__internal__/EventSource.addEventHandler.js";
import EventSource_buffer from "./EventSource/__internal__/EventSource.buffer.js";
import EventSource_create from "./EventSource/__internal__/EventSource.create.js";
import EventSource_createPublisher from "./EventSource/__internal__/EventSource.createPublisher.js";
import EventSource_createRefCountedPublisher from "./EventSource/__internal__/EventSource.createRefCountedPublisher.js";
import EventSource_distinctUntilChanged from "./EventSource/__internal__/EventSource.distinctUntilChanged.js";
import EventSource_keep from "./EventSource/__internal__/EventSource.keep.js";
import EventSource_keepType from "./EventSource/__internal__/EventSource.keepType.js";
import EventSource_keepWithKey from "./EventSource/__internal__/EventSource.keepWithKey.js";
import EventSource_map from "./EventSource/__internal__/EventSource.map.js";
import EventSource_mapTo from "./EventSource/__internal__/EventSource.mapTo.js";
import EventSource_mapWithKey from "./EventSource/__internal__/EventSource.mapWithKey.js";
import EventSource_merge from "./EventSource/__internal__/EventSource.merge.js";
import EventSource_mergeMany from "./EventSource/__internal__/EventSource.mergeMany.js";
import EventSource_pairwise from "./EventSource/__internal__/EventSource.pairwise.js";
import EventSource_pick from "./EventSource/__internal__/EventSource.pick.js";
import EventSource_scan from "./EventSource/__internal__/EventSource.scan.js";
import EventSource_skipFirst from "./EventSource/__internal__/EventSource.skipFirst.js";
import EventSource_takeFirst from "./EventSource/__internal__/EventSource.takeFirst.js";
import EventSource_takeLast from "./EventSource/__internal__/EventSource.takeLast.js";
import EventSource_takeWhile from "./EventSource/__internal__/EventSource.takeWhile.js";
import EventSource_toObservable from "./EventSource/__internal__/EventSource.toObservable.js";
import EventSource_toReadonlyArrayAsync from "./EventSource/__internal__/EventSource.toReadonlyArray.js";
import { identityLazy } from "./functions.js";
import { Container_type, } from "./types.js";
export const addEventHandler = EventSource_addEventHandler;
export const buffer = EventSource_buffer;
export const create = EventSource_create;
export const createPublisher = EventSource_createPublisher;
export const createRefCountedPublisher = EventSource_createRefCountedPublisher;
export const distinctUntilChanged = EventSource_distinctUntilChanged;
export const keep = EventSource_keep;
export const keepType = EventSource_keepType;
export const keepWithKey = EventSource_keepWithKey;
export const map = EventSource_map;
export const mapTo = EventSource_mapTo;
export const mapWithKey = EventSource_mapWithKey;
export const merge = EventSource_merge;
export const mergeMany = EventSource_mergeMany;
export const pairwise = EventSource_pairwise;
export const pick = EventSource_pick;
export const scan = EventSource_scan;
export const skipFirst = EventSource_skipFirst;
export const takeFirst = EventSource_takeFirst;
export const takeLast = EventSource_takeLast;
export const takeWhile = EventSource_takeWhile;
export const toEventSource = identityLazy;
export const toObservable = EventSource_toObservable;
export const toReadonlyArrayAsync = EventSource_toReadonlyArrayAsync;
