/// <reference types="./PauseableObservable.d.ts" />

import PauseableObservable_buffer from "./PauseableObservable/__internal__/PauseableObservable.buffer.js";
import PauseableObservable_distinctUntilChanged from "./PauseableObservable/__internal__/PauseableObservable.distinctUntilChanged.js";
import PauseableObservable_keep from "./PauseableObservable/__internal__/PauseableObservable.keep.js";
import PauseableObservable_keepType from "./PauseableObservable/__internal__/PauseableObservable.keepType.js";
import PauseableObservable_map from "./PauseableObservable/__internal__/PauseableObservable.map.js";
import PauseableObservable_mapTo from "./PauseableObservable/__internal__/PauseableObservable.mapTo.js";
import PauseableObservable_pairwise from "./PauseableObservable/__internal__/PauseableObservable.pairwise.js";
import PauseableObservable_pick from "./PauseableObservable/__internal__/PauseableObservable.pick.js";
import PauseableObservable_scan from "./PauseableObservable/__internal__/PauseableObservable.scan.js";
import PauseableObservable_sinkInto from "./PauseableObservable/__internal__/PauseableObservable.sinkInto.js";
import PauseableObservable_skipFirst from "./PauseableObservable/__internal__/PauseableObservable.skipFirst.js";
import PauseableObservable_takeFirst from "./PauseableObservable/__internal__/PauseableObservable.takeFirst.js";
import PauseableObservable_takeLast from "./PauseableObservable/__internal__/PauseableObservable.takeLast.js";
import PauseableObservable_takeWhile from "./PauseableObservable/__internal__/PauseableObservable.takeWhile.js";
import { Container_type, } from "./types.js";
export const buffer = PauseableObservable_buffer;
export const distinctUntilChanged = PauseableObservable_distinctUntilChanged;
export const keep = PauseableObservable_keep;
export const keepType = PauseableObservable_keepType;
export const map = PauseableObservable_map;
export const mapTo = PauseableObservable_mapTo;
export const pairwise = PauseableObservable_pairwise;
export const pick = PauseableObservable_pick;
export const scan = PauseableObservable_scan;
export const sinkInto = PauseableObservable_sinkInto;
export const skipFirst = PauseableObservable_skipFirst;
export const takeFirst = PauseableObservable_takeFirst;
export const takeLast = PauseableObservable_takeLast;
export const takeWhile = PauseableObservable_takeWhile;
