import { ReadonlyObjectMapContainer } from "./containers.js";
export declare const empty: ReadonlyObjectMapContainer.TypeClass["empty"];
export declare const entries: ReadonlyObjectMapContainer.TypeClass["entries"];
export declare const forEachWithKey: ReadonlyObjectMapContainer.TypeClass["forEachWithKey"];
export declare const keep: ReadonlyObjectMapContainer.TypeClass["keep"];
export declare const keepType: ReadonlyObjectMapContainer.TypeClass["keepType"];
export declare const keepWithKey: ReadonlyObjectMapContainer.TypeClass["keepWithKey"];
export declare const keys: ReadonlyObjectMapContainer.TypeClass["keys"];
export declare const keySet: ReadonlyObjectMapContainer.TypeClass["keySet"];
export declare const map: ReadonlyObjectMapContainer.TypeClass["map"];
export declare const mapWithKey: ReadonlyObjectMapContainer.TypeClass["mapWithKey"];
export declare const reduce: ReadonlyObjectMapContainer.TypeClass["reduce"];
export declare const reduceWithKey: ReadonlyObjectMapContainer.TypeClass["reduceWithKey"];
export declare const values: ReadonlyObjectMapContainer.TypeClass["values"];
