/// <reference types="./ReadonlyArray.d.ts" />

import Observable_toReadonlyArray from "./Observable/__internal__/Observable.toReadonlyArray.js";
import ReadonlyArray_buffer from "./ReadonlyArray/__internal__/ReadonlyArray.buffer.js";
import ReadonlyArray_distinctUntilChanged from "./ReadonlyArray/__internal__/ReadonlyArray.distinctUntilChanged.js";
import ReadonlyArray_empty from "./ReadonlyArray/__internal__/ReadonlyArray.empty.js";
import ReadonlyArray_entries from "./ReadonlyArray/__internal__/ReadonlyArray.entries.js";
import ReadonlyArray_enumerate from "./ReadonlyArray/__internal__/ReadonlyArray.enumerate.js";
import ReadonlyArray_forEach from "./ReadonlyArray/__internal__/ReadonlyArray.forEach.js";
import ReadonlyArray_forEachWithKey from "./ReadonlyArray/__internal__/ReadonlyArray.forEachWithKey.js";
import ReadonlyArray_fromFactory from "./ReadonlyArray/__internal__/ReadonlyArray.fromFactory.js";
import ReadonlyArray_fromIterable from "./ReadonlyArray/__internal__/ReadonlyArray.fromIterable.js";
import ReadonlyArray_fromOptional from "./ReadonlyArray/__internal__/ReadonlyArray.fromOptional.js";
import ReadonlyArray_fromValue from "./ReadonlyArray/__internal__/ReadonlyArray.fromValue.js";
import ReadonlyArray_keep from "./ReadonlyArray/__internal__/ReadonlyArray.keep.js";
import ReadonlyArray_keepWithKey from "./ReadonlyArray/__internal__/ReadonlyArray.keepWithKey.js";
import ReadonlyArray_keySet from "./ReadonlyArray/__internal__/ReadonlyArray.keySet.js";
import ReadonlyArray_keys from "./ReadonlyArray/__internal__/ReadonlyArray.keys.js";
import ReadonlyArray_map from "./ReadonlyArray/__internal__/ReadonlyArray.map.js";
import ReadonlyArray_mapWithKey from "./ReadonlyArray/__internal__/ReadonlyArray.mapWithKey.js";
import ReadonlyArray_pairwise from "./ReadonlyArray/__internal__/ReadonlyArray.pairwise.js";
import ReadonlyArray_reduce from "./ReadonlyArray/__internal__/ReadonlyArray.reduce.js";
import ReadonlyArray_reduceWithKey from "./ReadonlyArray/__internal__/ReadonlyArray.reduceWithKey.js";
import ReadonlyArray_scan from "./ReadonlyArray/__internal__/ReadonlyArray.scan.js";
import ReadonlyArray_skipFirst from "./ReadonlyArray/__internal__/ReadonlyArray.skipFirst.js";
import ReadonlyArray_takeFirst from "./ReadonlyArray/__internal__/ReadonlyArray.takeFirst.js";
import ReadonlyArray_takeLast from "./ReadonlyArray/__internal__/ReadonlyArray.takeLast.js";
import ReadonlyArray_takeWhile from "./ReadonlyArray/__internal__/ReadonlyArray.takeWhile.js";
import ReadonlyArray_toDictionary from "./ReadonlyArray/__internal__/ReadonlyArray.toDictionary.js";
import ReadonlyArray_toEventSource from "./ReadonlyArray/__internal__/ReadonlyArray.toEventSource.js";
import ReadonlyArray_toIndexedCollection from "./ReadonlyArray/__internal__/ReadonlyArray.toIndexedCollection.js";
import ReadonlyArray_toIterable from "./ReadonlyArray/__internal__/ReadonlyArray.toIterable.js";
import ReadonlyArray_toObservable from "./ReadonlyArray/__internal__/ReadonlyArray.toObservable.js";
import ReadonlyArray_toReadonlyArray from "./ReadonlyArray/__internal__/ReadonlyArray.toReadonlyArray.js";
import ReadonlyArray_values from "./ReadonlyArray/__internal__/ReadonlyArray.values.js";
import ReadonlyArray_toReadonlyMap from "./ReadonlyArray/__internal__/ReadonlyArrray.toReadonlyMap.js";
import { Container_type, } from "./types.js";
export const buffer = ReadonlyArray_buffer;
export const distinctUntilChanged = ReadonlyArray_distinctUntilChanged;
export const empty = ReadonlyArray_empty;
export const entries = ReadonlyArray_entries;
export const enumerate = ReadonlyArray_enumerate;
export const forEach = ReadonlyArray_forEach;
export const forEachWithKey = ReadonlyArray_forEachWithKey;
export const fromEnumerable = Observable_toReadonlyArray;
export const fromFactory = ReadonlyArray_fromFactory;
export const fromIterable = ReadonlyArray_fromIterable;
export const fromOptional = ReadonlyArray_fromOptional;
export const fromReadonlyArray = ReadonlyArray_toReadonlyArray;
export const fromValue = ReadonlyArray_fromValue;
export const keep = ReadonlyArray_keep;
export const keepWithKey = ReadonlyArray_keepWithKey;
export const keys = ReadonlyArray_keys;
export const keySet = ReadonlyArray_keySet;
export const map = ReadonlyArray_map;
export const pairwise = ReadonlyArray_pairwise;
export const mapWithKey = ReadonlyArray_mapWithKey;
export const reduce = ReadonlyArray_reduce;
export const reduceWithKey = ReadonlyArray_reduceWithKey;
export const scan = ReadonlyArray_scan;
export const skipFirst = ReadonlyArray_skipFirst;
export const takeFirst = ReadonlyArray_takeFirst;
export const takeLast = ReadonlyArray_takeLast;
export const takeWhile = ReadonlyArray_takeWhile;
export const toDictionary = ReadonlyArray_toDictionary;
export const toEventSource = ReadonlyArray_toEventSource;
export const toIndexedCollection = ReadonlyArray_toIndexedCollection;
export const toIterable = ReadonlyArray_toIterable;
export const toObservable = ReadonlyArray_toObservable;
export const toReadonlyArray = ReadonlyArray_toReadonlyArray;
export const toReadonlyMap = ReadonlyArray_toReadonlyMap;
export const values = ReadonlyArray_values;
