/// <reference types="./ReadonlyMap.d.ts" />

import ReadonlyMap_empty from "./ReadonlyMap/__internal__/ReadonlyMap.empty.js";
import ReadonlyMap_entries from "./ReadonlyMap/__internal__/ReadonlyMap.entries.js";
import ReadonlyMap_forEach from "./ReadonlyMap/__internal__/ReadonlyMap.forEach.js";
import ReadonlyMap_forEachWithKey from "./ReadonlyMap/__internal__/ReadonlyMap.forEachWithKey.js";
import ReadonlyMap_fromEntries from "./ReadonlyMap/__internal__/ReadonlyMap.fromEntries.js";
import ReadonlyMap_keep from "./ReadonlyMap/__internal__/ReadonlyMap.keep.js";
import ReadonlyMap_keepType from "./ReadonlyMap/__internal__/ReadonlyMap.keepType.js";
import ReadonlyMap_keepWithKey from "./ReadonlyMap/__internal__/ReadonlyMap.keepWithKey.js";
import ReadonlyMap_keySet from "./ReadonlyMap/__internal__/ReadonlyMap.keySet.js";
import ReadonlyMap_keys from "./ReadonlyMap/__internal__/ReadonlyMap.keys.js";
import ReadonlyMap_map from "./ReadonlyMap/__internal__/ReadonlyMap.map.js";
import ReadonlyMap_mapWithKey from "./ReadonlyMap/__internal__/ReadonlyMap.mapWithKey.js";
import ReadonlyMap_reduce from "./ReadonlyMap/__internal__/ReadonlyMap.reduce.js";
import ReadonlyMap_reduceWithKey from "./ReadonlyMap/__internal__/ReadonlyMap.reduceWithKey.js";
import ReadonlyMap_values from "./ReadonlyMap/__internal__/ReadonlyMap.values.js";
import { Container_type, KeyedContainer_TKey, } from "./types.js";
export const empty = ReadonlyMap_empty;
export const entries = ReadonlyMap_entries;
export const fromEntries = ReadonlyMap_fromEntries;
export const forEach = ReadonlyMap_forEach;
export const forEachWithKey = ReadonlyMap_forEachWithKey;
export const keep = ReadonlyMap_keep;
export const keepType = ReadonlyMap_keepType;
export const keepWithKey = ReadonlyMap_keepWithKey;
export const keys = ReadonlyMap_keys;
export const keySet = ReadonlyMap_keySet;
export const map = ReadonlyMap_map;
export const mapWithKey = ReadonlyMap_mapWithKey;
export const reduce = ReadonlyMap_reduce;
export const reduceWithKey = ReadonlyMap_reduceWithKey;
export const values = ReadonlyMap_values;
