name: build
"on":
  push:
    branches:
      - master
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn run lint
      - run: yarn run typecheck
      - run: yarn run test-coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
